import type { NextPage } from 'next';
import Head from 'next/head';
import { Title } from '@monorepo/components';
import { View, Text, Platform } from 'react-native';

const Home: NextPage = () => {
  return (
    <View>
      <Head>
        <title>Web NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
      <Text>Platform: {Platform.OS}</Text>
    </View>
  );
};

export default Home;
